#getprobe.R generated by Peter in Jan 09
#Modified by W. Timp 2/4/9

between <- function(num,lower,upper,strict=FALSE){
    if(strict)  return(num>lower & num<upper)
    if(!strict) return(num>=lower & num<=upper)
}

library(gdata)
x <- read.xls("~/thumper/Work/Notes/Genomics/Cancer DMRs/Regions/Cancer_dmr_shores.xls",sheet=2, pattern="distToCGI", header=TRUE)
load("~/cancer_dmr/From_Rafa/otherstuff.rda")
load("~/cancer_dmr/From_Rafa/sMM.rda")

#Number of probes to get
nummy <- 20


#Assigns subscript to j or k - which finds which things in
#names(INDEX) match
j <- which(names(INDEX)=="colon:normal")
k <- which(names(INDEX)=="colon:tumor")
#(names(INDEX) are column names for sMM)

sD <- sMM[,j]-sMM[,k]
sT <- sD/sqrt(ssigmas[,j]+ssigmas[,k])

#The genomic positions in pos are only meaningful when seen together with
#pns, which tells what chromosome they're on.  They index positions in the
#chromosome, not the whole genome.


#There's this whole thing in here about uniqueness - that's because
#there is overlap - due to both general overlap and due to the special
#chr11 region which is overcovered

#Strsplit splits the string into two strings around the second
#variable
#sapply applies function(v) - which basically tells it to take the
#first string.  The first string is going to be the chromosome
pnschr <- sapply(strsplit(pns,":"),function(v){return(v[1])})

stopifnot(identical(levels(as.factor(pns)),unique(pns)))
pbs   <- vector("list",length=nrow(x))
index <- vector("integer",length=nrow(x))
for(i in 1:nrow(x)){
    thischr <- which(pnschr==x[i,"chr"])
    pos0    <- pos[thischr]
    ins     <- which(between(pos0,x[i,2],x[i,3]))
    ans <- thischr[ins]
    pbs[[i]] <- ans
    
    pn <- unique(pns[ans])
    if(length(pn)==2 & pn[1]=="chr11:1900000-2900000") pn <- pn[2]
      #there are 2 of them and both are within the smaller subregion.
    index[i] <- which(unique(pns)==pn)
}
#pbs is the elements of pos(=>rows of sD and sT) that are between each DMR, going
#down the rows of x
#Check that index's chromosomes are right:
indexchr <- sapply(strsplit(unique(pns)[index],":"),function(v){return(v[1])})
stopifnot(all(indexchr==x[,1]))


#maxesT <- sapply(pbs,function(b){ which.max(abs(sT[b])) })
#maxesD <- sapply(pbs,function(b){ which.max(abs(sD[b])) })
#maxprobeT <- numeric(length=length(pbs))
#maxprobeD <- numeric(length=length(pbs))

#Initialize array - I'm going to want top nummy probes, along with their
#deltaM/cv values, for each region.

bestprobes <- array(0, dim=c(length(pbs),3,nummy))

for(i in 1:length(pbs)){

  #Get differences over variation for the probes in the relevant region
  region=sT[pbs[[i]]]
  sorted=sort(abs(region), index.return=TRUE, decreasing=TRUE)

  #Get probe locations
  bestprobes[i,1,]=pbs[[i]][sorted$ix[1:nummy]]
  #Get probe deltaMs
  bestprobes[i,2,]=sorted$x[1:nummy]

 
}


#Get probe coordinates
bestprobes[,3,] <- pos[bestprobes[,1,]]


#A check, to make sure these positions are inside the DMRs:
#I don't need the check - Timp                       
#for(k in 1:length(coordsT)){
#    stopifnot(between(coordsT[k],x[k,2],x[k,3]))
#    stopifnot(between(coordsD[k],x[k,2],x[k,3]))
#}


x$index <- index

for(i in 1:nummy){
  probe_loc = bestprobes[,3,i];
  probe_deltam = bestprobes[,2,i];

  x <- cbind(x, probe_loc)
  x <- cbind(x, probe_deltam)

}







write.csv(x,file="~/thumper/Work/Notes/Genomics/Cancer DMRs/Regions/Top_try.csv",row.names=FALSE,quote=FALSE)
 
#############################################################################
#Now for the plots:
#This code comes from results.R: 
